CodeCatz/TrackCat

templates/base.html, templates/pages/projects.html
done some basic playing with bootstrap
=> added test content and style with bootstrap

.gitignore, TrackCat/urls.py, TrackCat/views.py, templates/base.html, templates/pages/links.html
Page with useful links, where we can add links to tutorials, good practices, etc.
=> Added view with Links

templates/pages/members.html
Categories for members page propsed
=> Few more specifications for members page

templates/pages/members.html
Created the page with two profiles. 
Next, I will try to have the text of the right side of the picture in stead of having it below.
=> Members page: 2 imaginary kittens profiles

templates/pages/members.html
ok, hope no more unneeded spaces
=> corrected the unneeded spaces in Members

static/css/style.css, templates/base.html, templates/pages/about.html
this close #73  + About us changes to About CodeCatz
FYI @goranche ;)
=> larger images and font size adjustments

TrackCat/urls.py, TrackCat/views.py, web/templates/base.html, web/templates/pages/edituser.html, web/templates/pages/login.html
-Added User Profile management page with all settings -reference: Issue: #89 
-Added jQuery - reference to Issue #59
=> Added User Profile management page with all settings

coding-style.md
A quick reference for preferred best practices for HTML/CSS and more. Please read!
=> Coding style added

static/css/style.css, web/templates/pages/about.html, web/templates/pages/members.html
pictures moved from About to Members page
=> Issue #112 

web/templates/pages/project_detail.html, web/templates/pages/projects.html, web/urls.py, web/views.py
Created dynamic view and added dynamic data into project.html template
No particular design implemented, only a dynamic 4 column layout, some conditional data display.
Update:
The link behind the name of the project on the project list will open the new project detail page for this project.
Related to issue #116
=> Display dynamically the project list and the project details from the database

static/css/style.css, web/templates/base.html, web/templates/pages/events.html, web/templates/pages/links.html
=> Navigation bar "folding" fixed by making the content smaller

static/js/countdown.js, web/templates/base.html
Minor details that bothered me, but it might be just me ;)
=> removed console.log msgs in deadline notice

api/migrations/0002_auto_20150217_0824.py, api/models.py, static/css/jquery.datetimepicker.css, static/js/jquery.datetimepicker.js, web/form.py, web/templates/base.html, web/templates/pages/project_edit.html, web/templates/pages/projects.html, web/views.py
- defined html elements, classes
- added date picker
=> Added date picker on Project form 

web/form.py, web/templates/pages/project_edit.html
The project form is functioning again...
=> Reenabled datetimepicker to use both: date and time

web/templates/pages/project_detail.html, web/templates/pages/project_edit.html, web/views.py
If user sends request for some non existent project, will show a message instead of an error.
This closes #150
=> Added 404 error handling in views and templates for projects

coding-style.md
and some other small changes... mostly "fixes" to my bad markdown use
=> Added Python section to coding-style

web/form.py, web/templates/pages/project_detail.html, web/templates/pages/project_edit.html, web/templates/pages/projects.html
Fixes some inconsistent spacing and indentation in project template and project form pages
Closes #152
=> Fixes some inconsistent spacing and indentation

api/admin.py
=> Customized projects and tasks in admin interface

web/templates/base.html, web/templates/pages/project_edit.html
Fix for the javascript error bug
closes #184
=> Moved script for datetimepicker to the base.html

web/templates/base.html, web/views.py
Addressed issue #176.
We need to work on the link to member's profile and to edit the member's profile but first we somehow need to associate UserProfile with Github login information.
=> Login link in navigation

static/css/style.css
=> Fixes basic layout css issues

web/form.py, web/templates/pages/project_edit.html
=> Rewritten project form template to manual rendering

web/templates/pages/project_detail.html, web/templates/pages/projects.html, web/views.py
=> Added authentication restriction to project templates and views

web/views.py
Addressed @gandalfar comment in #186.
=> Fixed render for index.html in views.py

web/templates/base.html
=> Fixed Edit Profile link

web/templates/base.html
=> Added social media icons to footer

web/templates/base.html
To address #206  issue changed base page, added if/else for display of username in case first name/last name is missing for the user
=> Changed Menu to display username, if user does not have first name/last name set

web/templates/pages/members.html
On members page, added if statement, to check if member is active
=> Check if member is active, to display on members page

web/templates/pages/member_page.html, web/views.py
Display an error, in case of going to member-page with a non-existing user_id
=> Handle member detail page error, when member does not exist

static/css/style.css, web/templates/base.html, web/templates/pages/about.html, web/templates/pages/events.html, web/templates/pages/links.html, web/templates/pages/members.html, web/templates/pages/projects.html, web/templates/pages/tasks.html
Tabs are unified (titles and subtitles the same etc.) 
Content in About page has a narrower column then before to ease reading on computer 
Logo deleted from footer - no use having it in header AND footer
=> some minor design changes to make the whole page nicer

web/templates/pages/events.html, web/views.py
Get events from the database, and display on events page.
=> Added basic functionality to events page, to display events

web/form.py
Added user first_name and last_name to be able to update these in UserProfileForm
=> Update UserProfileForm to edit user first_name and last_name

web/templates/pages/members.html, web/views.py
Addressing #164. It groups and displays kittens. I will group mentors above kittens.
=> Group members according to activity_status

static/css/style.css
=> Fixed overlap between main content and footer

web/views.py
- excluded kitten instead of lazy in mentors_list
- excluded kitten beside mentors in kittens_list
Addressed @alja comment in @228.
=> Groupmembersbug included mojcas changes to the userprofile model

static/css/style.css, web/templates/pages/member_detail.html, web/templates/pages/members.html
- cleaned up unused selectors
- grouped selectors
=> Style.css cleanup

api/migrations/0008_auto_20150304_1249.py, api/models.py, web/form.py, web/templates/pages/project_edit.html
For now it's only with a default SelectMultiple widget.
Closes #198
=> Adding a many to many field to the Project form

static/css/style.css
=> Added min-height to wrap

web/templates/pages/project_detail.html, web/views.py
=> Loads related task list on project detail page

web/templates/pages/projects.html
=> Fixed the missing closing div in projects

web/templates/pages/events.html, web/templates/pages/members.html
=> Fixed the missing div closing tag in Members and Events

web/views.py
=> Errors when accessing URL of unexisting/deleted project

web/form.py
=> Cant add a deleted project on tasks

web/views.py
on tasks page and on task edit page
Fixes #247
=> Filter tasks to non deleted projects in querysets

web/templates/pages/events.html
Removed text about galery pictures from Events page
=> Events page

web/templates/base.html, web/templates/pages/project_detail.html, web/templates/pages/tasks.html
The Task menu item is now only for authenticated users, and the My tasks page show only tasks for the current user.
=> Implemented 'My tasks on task page and navbar'

web/templates/pages/project_detail.html
- deleted Add new project on Projects
- added Add new task to the project detail page
=> Reordered buttons on project pages

web/templates/pages/tasks.html
I thought it is better to have them under the task then below the title as I originally thought. 
Changed Add new to Add new task and closed a missing div.
Fixed indentation.
Addressing #267.
=> Changed buttons on My tasks to be the same as in project detail

web/form.py, web/templates/pages/member_edit.html
=> Update member update form,

web/form.py, web/templates/base.html, web/templates/pages/project_detail.html, web/views.py
Removed duplicate link to tasks, and protected view for logged in users only
Removed link to project from project detail page
=> Protected view for tasks - logged in user only

web/templates/pages/project_detail.html
Fixed project detail name to display username if there is no first name
=> Display username if user does not have first name set

web/templates/pages/events.html, web/templates/pages/members.html, web/templates/pages/projects.html, web/templates/pages/tasks.html
=> Fixed no members tasks events and projects message

web/templates/base.html, web/templates/pages/project_detail.html, web/templates/pages/projects.html, web/templates/pages/tasks.html
Renamed My Tasks to Tasks, and changed text for Edit project/task buttons
=> Fixed few smaller bugs

web/templates/base.html, web/templates/pages/tasks.html, web/views.py
=> Mytask shows assigned and owned tasks for the loged in user

web/form.py, web/templates/pages/member_detail.html
=> Add project labes and User website link

web/templates/pages/events.html, web/templates/pages/members.html
+ removed some trailing spaces
=> Removed page intros on events and members

web/templates/pages/events.html, web/templates/pages/member_detail.html
github link, members web site, links at events section
=> Open external links in a new window
